spring:
  application:
    name: crm-api

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=crm_pra_tu_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: bd_web02@
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    open-in-view: true